import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'es';

interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Translations> = {
  pt: {
    // ===== MENU =====
    'menu.home': 'Início',
    'menu.about': 'Quem Somos',
    'menu.events': 'Eventos',
    'menu.gallery': 'Galeria',
    'menu.prayer': 'Mural de Oração',
    'menu.donations': 'Doações',
    'menu.quiz': 'Quiz Bíblico',
    'menu.cells': 'Células',
    'menu.media': 'Mídia',
    'menu.contact': 'Contato',
    'menu.members': 'Membros',
    'menu.sundaySchool': 'Escolinha Dominical',
    'menu.more': 'Mais',
    'menu.login': 'Entrar',
    'menu.logout': 'Sair',
    'menu.memberArea': 'Área do Membro',
    'menu.adminPanel': 'Painel Admin',

    // ===== HERO SECTION =====
    'hero.welcome': 'Bem-vindo à',
    'hero.churchName': 'Igreja Conectada',
    'hero.subtitle': 'Um lugar de fé, amor e esperança. Conectando vidas a Deus e transformando histórias através do poder do Evangelho.',
    'hero.watchLive': 'Assistir ao Vivo',
    'hero.knowMore': 'Conhecer Mais',
    'hero.members': 'Membros',
    'hero.cells': 'Células',
    'hero.countries': 'Países',
    'hero.yearsMinistry': 'Anos de Ministério',

    // ===== VERSE POPUP =====
    'verse.dailyVerse': 'Versículo do Dia',
    'verse.amen': 'Amém',
    'verse.close': 'Fechar',
    'verse.shareVerse': 'Compartilhar Versículo',

    // ===== ABOUT SECTION =====
    'about.title': 'Quem Somos',
    'about.subtitle': 'Conheça nossa história, missão e os valores que nos guiam',
    'about.history': 'Nossa História',
    'about.historyText': 'A Igreja Conectada nasceu em 2010 com uma visão clara: conectar pessoas a Deus e umas às outras. O que começou como um pequeno grupo de oração em uma casa, hoje se tornou uma comunidade vibrante com milhares de membros em vários países.',
    'about.historyText2': 'Nossa jornada é marcada por milagres, transformações de vidas e um compromisso inabalável com o Evangelho de Jesus Cristo. Cada pessoa que passa por nossas portas encontra um lugar de acolhimento, amor e crescimento espiritual.',
    'about.mission': 'Missão',
    'about.missionText': 'Conectar pessoas a Deus e capacitá-las para viver uma vida plena em Cristo, impactando famílias e comunidades.',
    'about.vision': 'Visão',
    'about.visionText': 'Ser uma igreja relevante que transforma vidas através do amor de Cristo, alcançando todas as nações.',
    'about.values': 'Valores',
    'about.valuesText': 'Fé autêntica, amor incondicional, integridade, excelência no servir e compromisso com a Palavra de Deus.',
    'about.leadership': 'Nossa Liderança',
    'about.pastor': 'Pastor Presidente',
    'about.pastorDesc': 'Líder espiritual da nossa comunidade há mais de 15 anos, dedicado ao ensino da Palavra e ao cuidado pastoral.',
    'about.worship': 'Líder de Louvor',
    'about.worshipDesc': 'Ministrando através da música há 10 anos, conduzindo a igreja à presença de Deus com adoração genuína.',
    'about.coordinator': 'Coordenadora de Células',
    'about.coordinatorDesc': 'Responsável pelo crescimento e multiplicação das células, cuidando de cada líder e discipulado.',

    // ===== PRAYER WALL =====
    'prayer.title': 'Mural de Oração',
    'prayer.subtitle': 'Compartilhe seu pedido e ore pelos outros. Estamos juntos em oração!',
    'prayer.leaveRequest': 'Deixe seu Pedido',
    'prayer.name': 'Seu Nome',
    'prayer.namePlaceholder': 'Digite seu nome',
    'prayer.email': 'E-mail',
    'prayer.emailPlaceholder': 'Digite seu e-mail',
    'prayer.request': 'Seu Pedido de Oração',
    'prayer.requestPlaceholder': 'Compartilhe seu pedido de oração...',
    'prayer.type': 'Tipo de Pedido',
    'prayer.public': 'Público',
    'prayer.publicDesc': 'Visível para todos orarem juntos',
    'prayer.private': 'Privado',
    'prayer.privateDesc': 'Apenas a liderança terá acesso',
    'prayer.consent': 'Concordo com o tratamento dos meus dados conforme a LGPD/RGPD',
    'prayer.send': 'Enviar Pedido',
    'prayer.sending': 'Enviando...',
    'prayer.praying': 'Estou Orando',
    'prayer.peoplePraying': 'pessoas orando',
    'prayer.prayingNow': 'Pessoas Orando Agora',
    'prayer.anonymous': 'Anônimo',
    'prayer.requestSent': 'Pedido enviado com sucesso!',
    'prayer.requestSentPublic': 'Seu pedido foi publicado no mural de oração.',
    'prayer.requestSentPrivate': 'Seu pedido privado foi enviado à liderança.',
    'prayer.fillFields': 'Por favor, preencha todos os campos e aceite os termos.',
    'prayer.recentRequests': 'Pedidos Recentes',
    'prayer.noRequests': 'Nenhum pedido de oração ainda. Seja o primeiro!',
    'prayer.joinPrayer': 'Junte-se em Oração',

    // ===== EVENTS SECTION =====
    'events.title': 'Eventos',
    'events.subtitle': 'Participe dos nossos cultos e eventos especiais',
    'events.upcoming': 'Próximos Eventos',
    'events.calendar': 'Calendário',
    'events.addToCalendar': 'Adicionar à Agenda',
    'events.addedToCalendar': 'Evento adicionado à sua agenda!',
    'events.confirmPresence': 'Confirmar Presença',
    'events.presenceConfirmed': 'Presença confirmada!',
    'events.location': 'Local',
    'events.date': 'Data',
    'events.time': 'Horário',
    'events.preacher': 'Pregador',
    'events.singer': 'Louvor',
    'events.viewDetails': 'Ver Detalhes',
    'events.noEvents': 'Nenhum evento agendado no momento.',
    'events.sunday': 'Domingo',
    'events.monday': 'Segunda-feira',
    'events.tuesday': 'Terça-feira',
    'events.wednesday': 'Quarta-feira',
    'events.thursday': 'Quinta-feira',
    'events.friday': 'Sexta-feira',
    'events.saturday': 'Sábado',
    'events.jan': 'Janeiro',
    'events.feb': 'Fevereiro',
    'events.mar': 'Março',
    'events.apr': 'Abril',
    'events.may': 'Maio',
    'events.jun': 'Junho',
    'events.jul': 'Julho',
    'events.aug': 'Agosto',
    'events.sep': 'Setembro',
    'events.oct': 'Outubro',
    'events.nov': 'Novembro',
    'events.dec': 'Dezembro',

    // ===== GALLERY =====
    'gallery.title': 'Galeria',
    'gallery.subtitle': 'Momentos especiais da nossa comunidade',
    'gallery.all': 'Todos',
    'gallery.worship': 'Cultos',
    'gallery.events': 'Eventos',
    'gallery.cells': 'Células',
    'gallery.baptism': 'Batismos',
    'gallery.noPhotos': 'Nenhuma foto disponível ainda.',
    'gallery.viewMore': 'Ver Mais Fotos',
    'gallery.close': 'Fechar',
    'gallery.previous': 'Anterior',
    'gallery.next': 'Próxima',

    // ===== QUIZ =====
    'quiz.title': 'Quiz Bíblico',
    'quiz.subtitle': 'Teste seus conhecimentos bíblicos e divirta-se aprendendo!',
    'quiz.start': 'Iniciar Quiz',
    'quiz.yourName': 'Seu Nome',
    'quiz.namePlaceholder': 'Digite seu nome para o ranking',
    'quiz.question': 'Pergunta',
    'quiz.of': 'de',
    'quiz.timeLeft': 'Tempo restante',
    'quiz.seconds': 'segundos',
    'quiz.score': 'Pontuação',
    'quiz.points': 'pontos',
    'quiz.correct': 'Correto!',
    'quiz.incorrect': 'Incorreto!',
    'quiz.correctAnswer': 'Resposta correta',
    'quiz.next': 'Próxima',
    'quiz.finish': 'Finalizar',
    'quiz.completed': 'Quiz Concluído!',
    'quiz.yourScore': 'Sua Pontuação',
    'quiz.ranking': 'Ranking Global',
    'quiz.position': 'Posição',
    'quiz.player': 'Jogador',
    'quiz.playAgain': 'Jogar Novamente',
    'quiz.share': 'Compartilhar Resultado',
    'quiz.excellent': 'Excelente! Você é um verdadeiro estudioso da Bíblia! Continue assim!',
    'quiz.good': 'Muito bom! Você conhece bem as Escrituras. Continue estudando!',
    'quiz.average': 'Bom trabalho! Continue lendo a Bíblia para aprender mais.',
    'quiz.needsImprovement': 'Não desanime! A Palavra de Deus é rica. Continue estudando!',
    'quiz.noRanking': 'Nenhum jogador no ranking ainda.',
    'quiz.enterName': 'Digite seu nome para começar',

    // Quiz Questions
    'quiz.q1': 'Quantos livros tem a Bíblia?',
    'quiz.q1a1': '66',
    'quiz.q1a2': '72',
    'quiz.q1a3': '39',
    'quiz.q1a4': '27',
    'quiz.q2': 'Quem construiu a arca?',
    'quiz.q2a1': 'Noé',
    'quiz.q2a2': 'Moisés',
    'quiz.q2a3': 'Abraão',
    'quiz.q2a4': 'Davi',
    'quiz.q3': 'Qual é o maior mandamento segundo Jesus?',
    'quiz.q3a1': 'Amar a Deus sobre todas as coisas',
    'quiz.q3a2': 'Não matarás',
    'quiz.q3a3': 'Honrar pai e mãe',
    'quiz.q3a4': 'Não roubar',
    'quiz.q4': 'Quantos discípulos Jesus tinha?',
    'quiz.q4a1': '12',
    'quiz.q4a2': '7',
    'quiz.q4a3': '10',
    'quiz.q4a4': '3',
    'quiz.q5': 'Quem foi jogado na cova dos leões?',
    'quiz.q5a1': 'Daniel',
    'quiz.q5a2': 'Jonas',
    'quiz.q5a3': 'Elias',
    'quiz.q5a4': 'José',
    'quiz.q6': 'Onde Jesus nasceu?',
    'quiz.q6a1': 'Belém',
    'quiz.q6a2': 'Nazaré',
    'quiz.q6a3': 'Jerusalém',
    'quiz.q6a4': 'Cafarnaum',
    'quiz.q7': 'Quem batizou Jesus?',
    'quiz.q7a1': 'João Batista',
    'quiz.q7a2': 'Pedro',
    'quiz.q7a3': 'Paulo',
    'quiz.q7a4': 'Tiago',
    'quiz.q8': 'Quantos dias Jesus ficou no deserto?',
    'quiz.q8a1': '40',
    'quiz.q8a2': '30',
    'quiz.q8a3': '7',
    'quiz.q8a4': '12',
    'quiz.q9': 'Quem negou Jesus três vezes?',
    'quiz.q9a1': 'Pedro',
    'quiz.q9a2': 'Judas',
    'quiz.q9a3': 'Tomé',
    'quiz.q9a4': 'João',
    'quiz.q10': 'Qual é o primeiro livro da Bíblia?',
    'quiz.q10a1': 'Gênesis',
    'quiz.q10a2': 'Êxodo',
    'quiz.q10a3': 'Salmos',
    'quiz.q10a4': 'Mateus',

    // ===== DONATIONS =====
    'donations.title': 'Doações',
    'donations.subtitle': 'Sua generosidade transforma vidas e alcança nações',
    'donations.oneTime': 'Oferta Única',
    'donations.monthly': 'Mensal',
    'donations.custom': 'Outro valor',
    'donations.customPlaceholder': 'Digite o valor',
    'donations.method': 'Método de Pagamento',
    'donations.currency': 'Moeda',
    'donations.pix': 'PIX',
    'donations.mbway': 'MB WAY',
    'donations.transfer': 'Transferência Bancária',
    'donations.card': 'Cartão de Crédito',
    'donations.donate': 'Doar',
    'donations.donateNow': 'Doar Agora',
    'donations.processing': 'Processando...',
    'donations.thankYou': 'Obrigado pela sua doação!',
    'donations.receiptSent': 'Um recibo será enviado para seu e-mail.',
    'donations.projectGoals': 'Metas de Projetos',
    'donations.raised': 'arrecadado',
    'donations.goal': 'meta',
    'donations.contribute': 'Contribuir',
    'donations.supporters': 'apoiadores',
    'donations.missionTrip': 'Viagem Missionária',
    'donations.missionTripDesc': 'Envie missionários para pregar o Evangelho em regiões remotas.',
    'donations.buildingFund': 'Fundo de Construção',
    'donations.buildingFundDesc': 'Ampliação do templo para acomodar mais pessoas.',
    'donations.socialProject': 'Projeto Social',
    'donations.socialProjectDesc': 'Alimentação e apoio para famílias carentes da comunidade.',
    'donations.transparency': 'Transparência',
    'donations.transparencyText': 'Todas as doações são utilizadas com total transparência. Relatórios financeiros disponíveis para membros.',
    'donations.selectValue': 'Selecione um valor',
    'donations.email': 'E-mail para recibo',
    'donations.emailPlaceholder': 'seu@email.com',
    'donations.name': 'Nome completo',
    'donations.namePlaceholder': 'Seu nome',
    'donations.phone': 'Telefone',
    'donations.phonePlaceholder': 'Seu telefone',
    'donations.pixKey': 'Chave PIX',
    'donations.bankDetails': 'Dados Bancários',
    'donations.bank': 'Banco',
    'donations.agency': 'Agência',
    'donations.account': 'Conta',
    'donations.copyPix': 'Copiar Chave PIX',
    'donations.copied': 'Copiado!',

    // ===== CELLS =====
    'cells.title': 'Células',
    'cells.subtitle': 'Encontre uma célula perto de você e faça parte de uma família',
    'cells.map': 'Mapa de Células',
    'cells.findNearby': 'Encontrar Célula Próxima',
    'cells.leader': 'Líder',
    'cells.day': 'Dia',
    'cells.time': 'Horário',
    'cells.address': 'Endereço',
    'cells.participants': 'participantes',
    'cells.join': 'Participar',
    'cells.contact': 'Contato',
    'cells.noCells': 'Nenhuma célula cadastrada ainda.',
    'cells.whatAreCells': 'O que são Células?',
    'cells.whatAreCellsText': 'Células são pequenos grupos que se reúnem semanalmente em lares para estudar a Bíblia, orar e comungar juntos. É onde a vida cristã acontece de forma mais próxima e pessoal.',
    'cells.benefits': 'Benefícios',
    'cells.benefit1': 'Comunhão mais próxima',
    'cells.benefit2': 'Crescimento espiritual',
    'cells.benefit3': 'Apoio mútuo',
    'cells.benefit4': 'Discipulado pessoal',

    // ===== MEDIA =====
    'media.title': 'Mídia',
    'media.subtitle': 'Sermões, podcasts e conteúdos para edificar sua fé',
    'media.sermons': 'Sermões',
    'media.podcasts': 'Podcasts',
    'media.live': 'Ao Vivo',
    'media.watch': 'Assistir',
    'media.listen': 'Ouvir',
    'media.download': 'Baixar',
    'media.share': 'Compartilhar',
    'media.duration': 'Duração',
    'media.views': 'visualizações',
    'media.plays': 'reproduções',
    'media.noContent': 'Nenhum conteúdo disponível ainda.',
    'media.liveNow': 'AO VIVO AGORA',
    'media.watchLive': 'Assistir Transmissão',
    'media.notLive': 'Não estamos ao vivo no momento',
    'media.nextLive': 'Próxima transmissão',
    'media.subscribe': 'Inscreva-se no Canal',
    'media.latestSermons': 'Últimos Sermões',
    'media.latestPodcasts': 'Últimos Podcasts',
    'media.seeAll': 'Ver Todos',
    'media.recentEpisodes': 'Episódios Recentes',

    // ===== CONTACT =====
    'contact.title': 'Contato',
    'contact.subtitle': 'Entre em contato conosco. Estamos aqui para você!',
    'contact.getInTouch': 'Fale Conosco',
    'contact.name': 'Nome',
    'contact.namePlaceholder': 'Seu nome completo',
    'contact.email': 'E-mail',
    'contact.emailPlaceholder': 'seu@email.com',
    'contact.phone': 'Telefone',
    'contact.phonePlaceholder': '+351 900 000 000',
    'contact.subject': 'Assunto',
    'contact.subjectPlaceholder': 'Assunto da mensagem',
    'contact.message': 'Mensagem',
    'contact.messagePlaceholder': 'Escreva sua mensagem aqui...',
    'contact.send': 'Enviar Mensagem',
    'contact.sending': 'Enviando...',
    'contact.sent': 'Mensagem enviada com sucesso!',
    'contact.sentDesc': 'Responderemos em breve.',
    'contact.error': 'Erro ao enviar mensagem. Tente novamente.',
    'contact.fillFields': 'Por favor, preencha todos os campos.',
    'contact.address': 'Endereço',
    'contact.addressValue': 'Rua da Fé, 123 - Lisboa, Portugal',
    'contact.officeHours': 'Horário de Atendimento',
    'contact.officeHoursValue': 'Segunda a Sexta: 9h às 18h',
    'contact.followUs': 'Siga-nos',
    'contact.consent': 'Concordo com o tratamento dos meus dados pessoais',

    // ===== SUNDAY SCHOOL =====
    'sundaySchool.title': 'Escolinha Dominical',
    'sundaySchool.subtitle': 'Ensinando as crianças no caminho do Senhor',
    'sundaySchool.ages': 'Idades',
    'sundaySchool.schedule': 'Horário',
    'sundaySchool.teachers': 'Professores',
    'sundaySchool.materials': 'Materiais',
    'sundaySchool.register': 'Inscrever Criança',
    'sundaySchool.class1': 'Pequeninos (3-5 anos)',
    'sundaySchool.class2': 'Crianças (6-9 anos)',
    'sundaySchool.class3': 'Pré-adolescentes (10-12 anos)',

    // ===== FOOTER =====
    'footer.description': 'Conectando vidas a Deus e transformando histórias através do amor de Cristo.',
    'footer.quickLinks': 'Links Rápidos',
    'footer.contact': 'Contato',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Receba novidades e conteúdos edificantes.',
    'footer.emailPlaceholder': 'Seu e-mail',
    'footer.subscribe': 'Inscrever',
    'footer.subscribed': 'Inscrito com sucesso!',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Uso',
    'footer.lgpd': 'LGPD',

    // ===== LOGIN =====
    'login.title': 'Entrar',
    'login.subtitle': 'Acesse sua conta',
    'login.username': 'Usuário',
    'login.usernamePlaceholder': 'Digite seu usuário',
    'login.password': 'Senha',
    'login.passwordPlaceholder': 'Digite sua senha',
    'login.enter': 'Entrar',
    'login.entering': 'Entrando...',
    'login.forgotPassword': 'Esqueceu a senha?',
    'login.noAccount': 'Não tem conta?',
    'login.register': 'Cadastre-se',
    'login.error': 'Usuário ou senha inválidos',
    'login.adminHint': 'Admin: admin/123',
    'login.rememberMe': 'Lembrar de mim',
    'login.or': 'ou',
    'login.continueWith': 'Continuar com',
    'login.close': 'Fechar',

    // ===== MEMBER AREA =====
    'member.title': 'Área do Membro',
    'member.welcome': 'Bem-vindo',
    'member.profile': 'Meu Perfil',
    'member.donations': 'Minhas Doações',
    'member.courses': 'Meus Cursos',
    'member.certificates': 'Certificados',
    'member.materials': 'Materiais Exclusivos',
    'member.sundaySchool': 'Escolinha Dominical',
    'member.settings': 'Configurações',
    'member.editProfile': 'Editar Perfil',
    'member.changePassword': 'Alterar Senha',
    'member.notifications': 'Notificações',
    'member.donationHistory': 'Histórico de Doações',
    'member.downloadReceipt': 'Baixar Recibo',
    'member.noDonations': 'Nenhuma doação registrada.',
    'member.courseProgress': 'Progresso do Curso',
    'member.completed': 'Concluído',
    'member.inProgress': 'Em Andamento',
    'member.notStarted': 'Não Iniciado',
    'member.downloadCertificate': 'Baixar Certificado',
    'member.exclusiveMaterials': 'Materiais Exclusivos',
    'member.download': 'Baixar',
    'member.totalDonated': 'Total Doado',
    'member.memberSince': 'Membro desde',

    // ===== ADMIN PANEL =====
    'admin.title': 'Painel Administrativo',
    'admin.dashboard': 'Dashboard',
    'admin.members': 'Membros',
    'admin.events': 'Eventos',
    'admin.gallery': 'Galeria',
    'admin.prayers': 'Mural de Oração',
    'admin.live': 'Lives',
    'admin.settings': 'Configurações',
    'admin.newMember': 'Novo Membro',
    'admin.newEvent': 'Novo Evento',
    'admin.uploadPhotos': 'Upload de Fotos',
    'admin.startLive': 'Iniciar Live',
    'admin.totalMembers': 'Total de Membros',
    'admin.totalEvents': 'Total de Eventos',
    'admin.totalDonations': 'Total de Doações',
    'admin.pendingPrayers': 'Pedidos Pendentes',
    'admin.recentActivity': 'Atividade Recente',
    'admin.memberGrowth': 'Crescimento de Membros',
    'admin.attendanceRate': 'Taxa de Frequência',
    'admin.financialMetrics': 'Métricas Financeiras',
    'admin.edit': 'Editar',
    'admin.delete': 'Excluir',
    'admin.approve': 'Aprovar',
    'admin.reject': 'Rejeitar',
    'admin.pending': 'Pendente',
    'admin.approved': 'Aprovado',
    'admin.rejected': 'Rejeitado',
    'admin.save': 'Salvar',
    'admin.cancel': 'Cancelar',
    'admin.confirm': 'Confirmar',
    'admin.confirmDelete': 'Confirmar exclusão?',
    'admin.deleteWarning': 'Esta ação não pode ser desfeita.',
    'admin.name': 'Nome',
    'admin.email': 'E-mail',
    'admin.phone': 'Telefone',
    'admin.photo': 'Foto',
    'admin.status': 'Status',
    'admin.active': 'Ativo',
    'admin.inactive': 'Inativo',
    'admin.date': 'Data',
    'admin.time': 'Horário',
    'admin.location': 'Local',
    'admin.description': 'Descrição',
    'admin.poster': 'Pôster',
    'admin.pastorName': 'Nome do Pastor/Pregador',
    'admin.pastorPhoto': 'Foto do Pastor',
    'admin.singerName': 'Nome do Cantor/Ministério',
    'admin.singerPhoto': 'Foto do Cantor',
    'admin.eventPhotos': 'Fotos do Evento',
    'admin.category': 'Categoria',
    'admin.youtubeUrl': 'URL do YouTube',
    'admin.liveTitle': 'Título da Live',
    'admin.goLive': 'Ir ao Vivo',
    'admin.endLive': 'Encerrar Live',
    'admin.viewOnYoutube': 'Ver no YouTube',
    'admin.openChannel': 'Abrir Canal',
    'admin.privateRequests': 'Pedidos Privados',
    'admin.publicRequests': 'Pedidos Públicos',
    'admin.noMembers': 'Nenhum membro cadastrado.',
    'admin.noEvents': 'Nenhum evento cadastrado.',
    'admin.noPhotos': 'Nenhuma foto na galeria.',
    'admin.noPrayers': 'Nenhum pedido de oração.',
    'admin.uploadPhoto': 'Carregar Foto',
    'admin.selectPhoto': 'Selecionar Foto',
    'admin.dragDrop': 'Arraste e solte ou clique para selecionar',
    'admin.maxSize': 'Tamanho máximo: 5MB',
    'admin.selectCategory': 'Selecione uma categoria',
    'admin.addMember': 'Adicionar Membro',
    'admin.addEvent': 'Adicionar Evento',
    'admin.eventTitle': 'Título do Evento',
    'admin.eventDate': 'Data do Evento',
    'admin.eventTime': 'Horário do Evento',
    'admin.eventLocation': 'Local do Evento',
    'admin.eventDescription': 'Descrição do Evento',
    'admin.eventPoster': 'Pôster do Evento',
    'admin.monthlyDonations': 'Doações Mensais',
    'admin.weeklyAttendance': 'Frequência Semanal',
    'admin.liveSettings': 'Configurações de Live',
    'admin.channelUrl': 'URL do Canal',
    'admin.nextEvents': 'Próximos Eventos',
    'admin.searchMembers': 'Buscar membros...',
    'admin.filterByStatus': 'Filtrar por status',
    'admin.all': 'Todos',

    // ===== FLOATING WIDGETS =====
    'widget.talkToUs': 'Fale com um dos nossos',
    'widget.needHelp': 'Precisa de ajuda?',
    'widget.chatWhatsApp': 'Conversar no WhatsApp',
    'widget.nextService': 'Próximo Culto',
    'widget.confirmPresence': 'Confirmar Presença',
    'widget.yourName': 'Seu Nome',
    'widget.yourEmail': 'Seu E-mail',
    'widget.yourPhone': 'Seu Telefone',
    'widget.confirm': 'Confirmar',
    'widget.confirmed': 'Confirmado!',
    'widget.seeYou': 'Até lá! Deus abençoe.',
    'widget.close': 'Fechar',
    'widget.liveNow': 'Ao Vivo Agora',
    'widget.watchNow': 'Assistir Agora',
    'widget.serviceDetails': 'Detalhes do Culto',
    'widget.noUpcomingService': 'Nenhum culto programado',
    'widget.checkCalendar': 'Confira nosso calendário',

    // ===== COMMON =====
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.warning': 'Aviso',
    'common.info': 'Informação',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.ok': 'OK',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.close': 'Fechar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.more': 'Mais',
    'common.less': 'Menos',
    'common.seeMore': 'Ver mais',
    'common.seeLess': 'Ver menos',
    'common.viewAll': 'Ver todos',
    'common.required': 'Obrigatório',
    'common.optional': 'Opcional',
    'common.select': 'Selecionar',
    'common.selected': 'Selecionado',
    'common.noResults': 'Nenhum resultado encontrado',
    'common.tryAgain': 'Tente novamente',
    'common.refresh': 'Atualizar',
    'common.share': 'Compartilhar',
    'common.copy': 'Copiar',
    'common.copied': 'Copiado!',
    'common.download': 'Baixar',
    'common.upload': 'Enviar',
    'common.send': 'Enviar',
    'common.submit': 'Enviar',
    'common.continue': 'Continuar',
    'common.finish': 'Finalizar',
    'common.start': 'Iniciar',
    'common.stop': 'Parar',
    'common.pause': 'Pausar',
    'common.play': 'Reproduzir',
    'common.today': 'Hoje',
    'common.yesterday': 'Ontem',
    'common.tomorrow': 'Amanhã',
    'common.thisWeek': 'Esta semana',
    'common.thisMonth': 'Este mês',
    'common.thisYear': 'Este ano',
  },
  en: {
    // ===== MENU =====
    'menu.home': 'Home',
    'menu.about': 'About Us',
    'menu.events': 'Events',
    'menu.gallery': 'Gallery',
    'menu.prayer': 'Prayer Wall',
    'menu.donations': 'Donations',
    'menu.quiz': 'Bible Quiz',
    'menu.cells': 'Cell Groups',
    'menu.media': 'Media',
    'menu.contact': 'Contact',
    'menu.members': 'Members',
    'menu.sundaySchool': 'Sunday School',
    'menu.more': 'More',
    'menu.login': 'Login',
    'menu.logout': 'Logout',
    'menu.memberArea': 'Member Area',
    'menu.adminPanel': 'Admin Panel',

    // ===== HERO SECTION =====
    'hero.welcome': 'Welcome to',
    'hero.churchName': 'Connected Church',
    'hero.subtitle': 'A place of faith, love and hope. Connecting lives to God and transforming stories through the power of the Gospel.',
    'hero.watchLive': 'Watch Live',
    'hero.knowMore': 'Learn More',
    'hero.members': 'Members',
    'hero.cells': 'Cell Groups',
    'hero.countries': 'Countries',
    'hero.yearsMinistry': 'Years of Ministry',

    // ===== VERSE POPUP =====
    'verse.dailyVerse': 'Verse of the Day',
    'verse.amen': 'Amen',
    'verse.close': 'Close',
    'verse.shareVerse': 'Share Verse',

    // ===== ABOUT SECTION =====
    'about.title': 'About Us',
    'about.subtitle': 'Learn about our history, mission and the values that guide us',
    'about.history': 'Our History',
    'about.historyText': 'Connected Church was born in 2010 with a clear vision: to connect people to God and to each other. What started as a small prayer group in a home has now become a vibrant community with thousands of members in several countries.',
    'about.historyText2': 'Our journey is marked by miracles, life transformations and an unwavering commitment to the Gospel of Jesus Christ. Every person who walks through our doors finds a place of welcome, love and spiritual growth.',
    'about.mission': 'Mission',
    'about.missionText': 'To connect people to God and empower them to live a full life in Christ, impacting families and communities.',
    'about.vision': 'Vision',
    'about.visionText': 'To be a relevant church that transforms lives through the love of Christ, reaching all nations.',
    'about.values': 'Values',
    'about.valuesText': 'Authentic faith, unconditional love, integrity, excellence in service and commitment to the Word of God.',
    'about.leadership': 'Our Leadership',
    'about.pastor': 'Senior Pastor',
    'about.pastorDesc': 'Spiritual leader of our community for over 15 years, dedicated to teaching the Word and pastoral care.',
    'about.worship': 'Worship Leader',
    'about.worshipDesc': 'Ministering through music for 10 years, leading the church into God\'s presence with genuine worship.',
    'about.coordinator': 'Cell Coordinator',
    'about.coordinatorDesc': 'Responsible for the growth and multiplication of cells, caring for each leader and discipleship.',

    // ===== PRAYER WALL =====
    'prayer.title': 'Prayer Wall',
    'prayer.subtitle': 'Share your request and pray for others. We are together in prayer!',
    'prayer.leaveRequest': 'Leave Your Request',
    'prayer.name': 'Your Name',
    'prayer.namePlaceholder': 'Enter your name',
    'prayer.email': 'Email',
    'prayer.emailPlaceholder': 'Enter your email',
    'prayer.request': 'Your Prayer Request',
    'prayer.requestPlaceholder': 'Share your prayer request...',
    'prayer.type': 'Request Type',
    'prayer.public': 'Public',
    'prayer.publicDesc': 'Visible for everyone to pray together',
    'prayer.private': 'Private',
    'prayer.privateDesc': 'Only leadership will have access',
    'prayer.consent': 'I agree to the processing of my data according to GDPR',
    'prayer.send': 'Send Request',
    'prayer.sending': 'Sending...',
    'prayer.praying': 'I\'m Praying',
    'prayer.peoplePraying': 'people praying',
    'prayer.prayingNow': 'People Praying Now',
    'prayer.anonymous': 'Anonymous',
    'prayer.requestSent': 'Request sent successfully!',
    'prayer.requestSentPublic': 'Your request has been published on the prayer wall.',
    'prayer.requestSentPrivate': 'Your private request has been sent to leadership.',
    'prayer.fillFields': 'Please fill in all fields and accept the terms.',
    'prayer.recentRequests': 'Recent Requests',
    'prayer.noRequests': 'No prayer requests yet. Be the first!',
    'prayer.joinPrayer': 'Join in Prayer',

    // ===== EVENTS SECTION =====
    'events.title': 'Events',
    'events.subtitle': 'Join our services and special events',
    'events.upcoming': 'Upcoming Events',
    'events.calendar': 'Calendar',
    'events.addToCalendar': 'Add to Calendar',
    'events.addedToCalendar': 'Event added to your calendar!',
    'events.confirmPresence': 'Confirm Attendance',
    'events.presenceConfirmed': 'Attendance confirmed!',
    'events.location': 'Location',
    'events.date': 'Date',
    'events.time': 'Time',
    'events.preacher': 'Preacher',
    'events.singer': 'Worship',
    'events.viewDetails': 'View Details',
    'events.noEvents': 'No events scheduled at the moment.',
    'events.sunday': 'Sunday',
    'events.monday': 'Monday',
    'events.tuesday': 'Tuesday',
    'events.wednesday': 'Wednesday',
    'events.thursday': 'Thursday',
    'events.friday': 'Friday',
    'events.saturday': 'Saturday',
    'events.jan': 'January',
    'events.feb': 'February',
    'events.mar': 'March',
    'events.apr': 'April',
    'events.may': 'May',
    'events.jun': 'June',
    'events.jul': 'July',
    'events.aug': 'August',
    'events.sep': 'September',
    'events.oct': 'October',
    'events.nov': 'November',
    'events.dec': 'December',

    // ===== GALLERY =====
    'gallery.title': 'Gallery',
    'gallery.subtitle': 'Special moments from our community',
    'gallery.all': 'All',
    'gallery.worship': 'Services',
    'gallery.events': 'Events',
    'gallery.cells': 'Cell Groups',
    'gallery.baptism': 'Baptisms',
    'gallery.noPhotos': 'No photos available yet.',
    'gallery.viewMore': 'View More Photos',
    'gallery.close': 'Close',
    'gallery.previous': 'Previous',
    'gallery.next': 'Next',

    // ===== QUIZ =====
    'quiz.title': 'Bible Quiz',
    'quiz.subtitle': 'Test your biblical knowledge and have fun learning!',
    'quiz.start': 'Start Quiz',
    'quiz.yourName': 'Your Name',
    'quiz.namePlaceholder': 'Enter your name for the ranking',
    'quiz.question': 'Question',
    'quiz.of': 'of',
    'quiz.timeLeft': 'Time left',
    'quiz.seconds': 'seconds',
    'quiz.score': 'Score',
    'quiz.points': 'points',
    'quiz.correct': 'Correct!',
    'quiz.incorrect': 'Incorrect!',
    'quiz.correctAnswer': 'Correct answer',
    'quiz.next': 'Next',
    'quiz.finish': 'Finish',
    'quiz.completed': 'Quiz Completed!',
    'quiz.yourScore': 'Your Score',
    'quiz.ranking': 'Global Ranking',
    'quiz.position': 'Position',
    'quiz.player': 'Player',
    'quiz.playAgain': 'Play Again',
    'quiz.share': 'Share Result',
    'quiz.excellent': 'Excellent! You are a true Bible scholar! Keep it up!',
    'quiz.good': 'Very good! You know the Scriptures well. Keep studying!',
    'quiz.average': 'Good job! Keep reading the Bible to learn more.',
    'quiz.needsImprovement': 'Don\'t give up! God\'s Word is rich. Keep studying!',
    'quiz.noRanking': 'No players in the ranking yet.',
    'quiz.enterName': 'Enter your name to start',

    // Quiz Questions
    'quiz.q1': 'How many books are in the Bible?',
    'quiz.q1a1': '66',
    'quiz.q1a2': '72',
    'quiz.q1a3': '39',
    'quiz.q1a4': '27',
    'quiz.q2': 'Who built the ark?',
    'quiz.q2a1': 'Noah',
    'quiz.q2a2': 'Moses',
    'quiz.q2a3': 'Abraham',
    'quiz.q2a4': 'David',
    'quiz.q3': 'What is the greatest commandment according to Jesus?',
    'quiz.q3a1': 'Love God above all things',
    'quiz.q3a2': 'You shall not kill',
    'quiz.q3a3': 'Honor your father and mother',
    'quiz.q3a4': 'You shall not steal',
    'quiz.q4': 'How many disciples did Jesus have?',
    'quiz.q4a1': '12',
    'quiz.q4a2': '7',
    'quiz.q4a3': '10',
    'quiz.q4a4': '3',
    'quiz.q5': 'Who was thrown into the lions\' den?',
    'quiz.q5a1': 'Daniel',
    'quiz.q5a2': 'Jonah',
    'quiz.q5a3': 'Elijah',
    'quiz.q5a4': 'Joseph',
    'quiz.q6': 'Where was Jesus born?',
    'quiz.q6a1': 'Bethlehem',
    'quiz.q6a2': 'Nazareth',
    'quiz.q6a3': 'Jerusalem',
    'quiz.q6a4': 'Capernaum',
    'quiz.q7': 'Who baptized Jesus?',
    'quiz.q7a1': 'John the Baptist',
    'quiz.q7a2': 'Peter',
    'quiz.q7a3': 'Paul',
    'quiz.q7a4': 'James',
    'quiz.q8': 'How many days did Jesus spend in the desert?',
    'quiz.q8a1': '40',
    'quiz.q8a2': '30',
    'quiz.q8a3': '7',
    'quiz.q8a4': '12',
    'quiz.q9': 'Who denied Jesus three times?',
    'quiz.q9a1': 'Peter',
    'quiz.q9a2': 'Judas',
    'quiz.q9a3': 'Thomas',
    'quiz.q9a4': 'John',
    'quiz.q10': 'What is the first book of the Bible?',
    'quiz.q10a1': 'Genesis',
    'quiz.q10a2': 'Exodus',
    'quiz.q10a3': 'Psalms',
    'quiz.q10a4': 'Matthew',

    // ===== DONATIONS =====
    'donations.title': 'Donations',
    'donations.subtitle': 'Your generosity transforms lives and reaches nations',
    'donations.oneTime': 'One-Time Gift',
    'donations.monthly': 'Monthly',
    'donations.custom': 'Other amount',
    'donations.customPlaceholder': 'Enter amount',
    'donations.method': 'Payment Method',
    'donations.currency': 'Currency',
    'donations.pix': 'PIX',
    'donations.mbway': 'MB WAY',
    'donations.transfer': 'Bank Transfer',
    'donations.card': 'Credit Card',
    'donations.donate': 'Donate',
    'donations.donateNow': 'Donate Now',
    'donations.processing': 'Processing...',
    'donations.thankYou': 'Thank you for your donation!',
    'donations.receiptSent': 'A receipt will be sent to your email.',
    'donations.projectGoals': 'Project Goals',
    'donations.raised': 'raised',
    'donations.goal': 'goal',
    'donations.contribute': 'Contribute',
    'donations.supporters': 'supporters',
    'donations.missionTrip': 'Mission Trip',
    'donations.missionTripDesc': 'Send missionaries to preach the Gospel in remote regions.',
    'donations.buildingFund': 'Building Fund',
    'donations.buildingFundDesc': 'Temple expansion to accommodate more people.',
    'donations.socialProject': 'Social Project',
    'donations.socialProjectDesc': 'Food and support for needy families in the community.',
    'donations.transparency': 'Transparency',
    'donations.transparencyText': 'All donations are used with full transparency. Financial reports available for members.',
    'donations.selectValue': 'Select an amount',
    'donations.email': 'Email for receipt',
    'donations.emailPlaceholder': 'your@email.com',
    'donations.name': 'Full name',
    'donations.namePlaceholder': 'Your name',
    'donations.phone': 'Phone',
    'donations.phonePlaceholder': 'Your phone',
    'donations.pixKey': 'PIX Key',
    'donations.bankDetails': 'Bank Details',
    'donations.bank': 'Bank',
    'donations.agency': 'Agency',
    'donations.account': 'Account',
    'donations.copyPix': 'Copy PIX Key',
    'donations.copied': 'Copied!',

    // ===== CELLS =====
    'cells.title': 'Cell Groups',
    'cells.subtitle': 'Find a cell group near you and become part of a family',
    'cells.map': 'Cell Map',
    'cells.findNearby': 'Find Nearby Cell',
    'cells.leader': 'Leader',
    'cells.day': 'Day',
    'cells.time': 'Time',
    'cells.address': 'Address',
    'cells.participants': 'participants',
    'cells.join': 'Join',
    'cells.contact': 'Contact',
    'cells.noCells': 'No cell groups registered yet.',
    'cells.whatAreCells': 'What are Cell Groups?',
    'cells.whatAreCellsText': 'Cell groups are small groups that meet weekly in homes to study the Bible, pray and fellowship together. It\'s where Christian life happens in a closer and more personal way.',
    'cells.benefits': 'Benefits',
    'cells.benefit1': 'Closer fellowship',
    'cells.benefit2': 'Spiritual growth',
    'cells.benefit3': 'Mutual support',
    'cells.benefit4': 'Personal discipleship',

    // ===== MEDIA =====
    'media.title': 'Media',
    'media.subtitle': 'Sermons, podcasts and content to edify your faith',
    'media.sermons': 'Sermons',
    'media.podcasts': 'Podcasts',
    'media.live': 'Live',
    'media.watch': 'Watch',
    'media.listen': 'Listen',
    'media.download': 'Download',
    'media.share': 'Share',
    'media.duration': 'Duration',
    'media.views': 'views',
    'media.plays': 'plays',
    'media.noContent': 'No content available yet.',
    'media.liveNow': 'LIVE NOW',
    'media.watchLive': 'Watch Broadcast',
    'media.notLive': 'We are not live at the moment',
    'media.nextLive': 'Next broadcast',
    'media.subscribe': 'Subscribe to Channel',
    'media.latestSermons': 'Latest Sermons',
    'media.latestPodcasts': 'Latest Podcasts',
    'media.seeAll': 'See All',
    'media.recentEpisodes': 'Recent Episodes',

    // ===== CONTACT =====
    'contact.title': 'Contact',
    'contact.subtitle': 'Get in touch with us. We are here for you!',
    'contact.getInTouch': 'Get in Touch',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your full name',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.phone': 'Phone',
    'contact.phonePlaceholder': '+351 900 000 000',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'Message subject',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Write your message here...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.sent': 'Message sent successfully!',
    'contact.sentDesc': 'We will respond shortly.',
    'contact.error': 'Error sending message. Try again.',
    'contact.fillFields': 'Please fill in all fields.',
    'contact.address': 'Address',
    'contact.addressValue': 'Faith Street, 123 - Lisbon, Portugal',
    'contact.officeHours': 'Office Hours',
    'contact.officeHoursValue': 'Monday to Friday: 9am to 6pm',
    'contact.followUs': 'Follow Us',
    'contact.consent': 'I agree to the processing of my personal data',

    // ===== SUNDAY SCHOOL =====
    'sundaySchool.title': 'Sunday School',
    'sundaySchool.subtitle': 'Teaching children in the way of the Lord',
    'sundaySchool.ages': 'Ages',
    'sundaySchool.schedule': 'Schedule',
    'sundaySchool.teachers': 'Teachers',
    'sundaySchool.materials': 'Materials',
    'sundaySchool.register': 'Register Child',
    'sundaySchool.class1': 'Little Ones (3-5 years)',
    'sundaySchool.class2': 'Children (6-9 years)',
    'sundaySchool.class3': 'Pre-teens (10-12 years)',

    // ===== FOOTER =====
    'footer.description': 'Connecting lives to God and transforming stories through the love of Christ.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Receive news and edifying content.',
    'footer.emailPlaceholder': 'Your email',
    'footer.subscribe': 'Subscribe',
    'footer.subscribed': 'Subscribed successfully!',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.lgpd': 'GDPR',

    // ===== LOGIN =====
    'login.title': 'Login',
    'login.subtitle': 'Access your account',
    'login.username': 'Username',
    'login.usernamePlaceholder': 'Enter your username',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.enter': 'Login',
    'login.entering': 'Logging in...',
    'login.forgotPassword': 'Forgot password?',
    'login.noAccount': 'Don\'t have an account?',
    'login.register': 'Register',
    'login.error': 'Invalid username or password',
    'login.adminHint': 'Admin: admin/123',
    'login.rememberMe': 'Remember me',
    'login.or': 'or',
    'login.continueWith': 'Continue with',
    'login.close': 'Close',

    // ===== MEMBER AREA =====
    'member.title': 'Member Area',
    'member.welcome': 'Welcome',
    'member.profile': 'My Profile',
    'member.donations': 'My Donations',
    'member.courses': 'My Courses',
    'member.certificates': 'Certificates',
    'member.materials': 'Exclusive Materials',
    'member.sundaySchool': 'Sunday School',
    'member.settings': 'Settings',
    'member.editProfile': 'Edit Profile',
    'member.changePassword': 'Change Password',
    'member.notifications': 'Notifications',
    'member.donationHistory': 'Donation History',
    'member.downloadReceipt': 'Download Receipt',
    'member.noDonations': 'No donations recorded.',
    'member.courseProgress': 'Course Progress',
    'member.completed': 'Completed',
    'member.inProgress': 'In Progress',
    'member.notStarted': 'Not Started',
    'member.downloadCertificate': 'Download Certificate',
    'member.exclusiveMaterials': 'Exclusive Materials',
    'member.download': 'Download',
    'member.totalDonated': 'Total Donated',
    'member.memberSince': 'Member since',

    // ===== ADMIN PANEL =====
    'admin.title': 'Admin Panel',
    'admin.dashboard': 'Dashboard',
    'admin.members': 'Members',
    'admin.events': 'Events',
    'admin.gallery': 'Gallery',
    'admin.prayers': 'Prayer Wall',
    'admin.live': 'Lives',
    'admin.settings': 'Settings',
    'admin.newMember': 'New Member',
    'admin.newEvent': 'New Event',
    'admin.uploadPhotos': 'Upload Photos',
    'admin.startLive': 'Start Live',
    'admin.totalMembers': 'Total Members',
    'admin.totalEvents': 'Total Events',
    'admin.totalDonations': 'Total Donations',
    'admin.pendingPrayers': 'Pending Requests',
    'admin.recentActivity': 'Recent Activity',
    'admin.memberGrowth': 'Member Growth',
    'admin.attendanceRate': 'Attendance Rate',
    'admin.financialMetrics': 'Financial Metrics',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.pending': 'Pending',
    'admin.approved': 'Approved',
    'admin.rejected': 'Rejected',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.confirm': 'Confirm',
    'admin.confirmDelete': 'Confirm deletion?',
    'admin.deleteWarning': 'This action cannot be undone.',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.phone': 'Phone',
    'admin.photo': 'Photo',
    'admin.status': 'Status',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.date': 'Date',
    'admin.time': 'Time',
    'admin.location': 'Location',
    'admin.description': 'Description',
    'admin.poster': 'Poster',
    'admin.pastorName': 'Pastor/Preacher Name',
    'admin.pastorPhoto': 'Pastor Photo',
    'admin.singerName': 'Singer/Ministry Name',
    'admin.singerPhoto': 'Singer Photo',
    'admin.eventPhotos': 'Event Photos',
    'admin.category': 'Category',
    'admin.youtubeUrl': 'YouTube URL',
    'admin.liveTitle': 'Live Title',
    'admin.goLive': 'Go Live',
    'admin.endLive': 'End Live',
    'admin.viewOnYoutube': 'View on YouTube',
    'admin.openChannel': 'Open Channel',
    'admin.privateRequests': 'Private Requests',
    'admin.publicRequests': 'Public Requests',
    'admin.noMembers': 'No members registered.',
    'admin.noEvents': 'No events registered.',
    'admin.noPhotos': 'No photos in gallery.',
    'admin.noPrayers': 'No prayer requests.',
    'admin.uploadPhoto': 'Upload Photo',
    'admin.selectPhoto': 'Select Photo',
    'admin.dragDrop': 'Drag and drop or click to select',
    'admin.maxSize': 'Maximum size: 5MB',
    'admin.selectCategory': 'Select a category',
    'admin.addMember': 'Add Member',
    'admin.addEvent': 'Add Event',
    'admin.eventTitle': 'Event Title',
    'admin.eventDate': 'Event Date',
    'admin.eventTime': 'Event Time',
    'admin.eventLocation': 'Event Location',
    'admin.eventDescription': 'Event Description',
    'admin.eventPoster': 'Event Poster',
    'admin.monthlyDonations': 'Monthly Donations',
    'admin.weeklyAttendance': 'Weekly Attendance',
    'admin.liveSettings': 'Live Settings',
    'admin.channelUrl': 'Channel URL',
    'admin.nextEvents': 'Next Events',
    'admin.searchMembers': 'Search members...',
    'admin.filterByStatus': 'Filter by status',
    'admin.all': 'All',

    // ===== FLOATING WIDGETS =====
    'widget.talkToUs': 'Talk to one of us',
    'widget.needHelp': 'Need help?',
    'widget.chatWhatsApp': 'Chat on WhatsApp',
    'widget.nextService': 'Next Service',
    'widget.confirmPresence': 'Confirm Attendance',
    'widget.yourName': 'Your Name',
    'widget.yourEmail': 'Your Email',
    'widget.yourPhone': 'Your Phone',
    'widget.confirm': 'Confirm',
    'widget.confirmed': 'Confirmed!',
    'widget.seeYou': 'See you there! God bless.',
    'widget.close': 'Close',
    'widget.liveNow': 'Live Now',
    'widget.watchNow': 'Watch Now',
    'widget.serviceDetails': 'Service Details',
    'widget.noUpcomingService': 'No scheduled service',
    'widget.checkCalendar': 'Check our calendar',

    // ===== COMMON =====
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.more': 'More',
    'common.less': 'Less',
    'common.seeMore': 'See more',
    'common.seeLess': 'See less',
    'common.viewAll': 'View all',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.select': 'Select',
    'common.selected': 'Selected',
    'common.noResults': 'No results found',
    'common.tryAgain': 'Try again',
    'common.refresh': 'Refresh',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.copied': 'Copied!',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.send': 'Send',
    'common.submit': 'Submit',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.play': 'Play',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.tomorrow': 'Tomorrow',
    'common.thisWeek': 'This week',
    'common.thisMonth': 'This month',
    'common.thisYear': 'This year',
  },
  es: {
    // ===== MENU =====
    'menu.home': 'Inicio',
    'menu.about': 'Quiénes Somos',
    'menu.events': 'Eventos',
    'menu.gallery': 'Galería',
    'menu.prayer': 'Muro de Oración',
    'menu.donations': 'Donaciones',
    'menu.quiz': 'Quiz Bíblico',
    'menu.cells': 'Células',
    'menu.media': 'Medios',
    'menu.contact': 'Contacto',
    'menu.members': 'Miembros',
    'menu.sundaySchool': 'Escuela Dominical',
    'menu.more': 'Más',
    'menu.login': 'Entrar',
    'menu.logout': 'Salir',
    'menu.memberArea': 'Área del Miembro',
    'menu.adminPanel': 'Panel Admin',

    // ===== HERO SECTION =====
    'hero.welcome': 'Bienvenido a',
    'hero.churchName': 'Iglesia Conectada',
    'hero.subtitle': 'Un lugar de fe, amor y esperanza. Conectando vidas a Dios y transformando historias a través del poder del Evangelio.',
    'hero.watchLive': 'Ver en Vivo',
    'hero.knowMore': 'Conocer Más',
    'hero.members': 'Miembros',
    'hero.cells': 'Células',
    'hero.countries': 'Países',
    'hero.yearsMinistry': 'Años de Ministerio',

    // ===== VERSE POPUP =====
    'verse.dailyVerse': 'Versículo del Día',
    'verse.amen': 'Amén',
    'verse.close': 'Cerrar',
    'verse.shareVerse': 'Compartir Versículo',

    // ===== ABOUT SECTION =====
    'about.title': 'Quiénes Somos',
    'about.subtitle': 'Conoce nuestra historia, misión y los valores que nos guían',
    'about.history': 'Nuestra Historia',
    'about.historyText': 'La Iglesia Conectada nació en 2010 con una visión clara: conectar personas a Dios y entre sí. Lo que comenzó como un pequeño grupo de oración en una casa, hoy se ha convertido en una comunidad vibrante con miles de miembros en varios países.',
    'about.historyText2': 'Nuestro viaje está marcado por milagros, transformaciones de vidas y un compromiso inquebrantable con el Evangelio de Jesucristo. Cada persona que pasa por nuestras puertas encuentra un lugar de acogida, amor y crecimiento espiritual.',
    'about.mission': 'Misión',
    'about.missionText': 'Conectar personas a Dios y capacitarlas para vivir una vida plena en Cristo, impactando familias y comunidades.',
    'about.vision': 'Visión',
    'about.visionText': 'Ser una iglesia relevante que transforma vidas a través del amor de Cristo, alcanzando todas las naciones.',
    'about.values': 'Valores',
    'about.valuesText': 'Fe auténtica, amor incondicional, integridad, excelencia en el servicio y compromiso con la Palabra de Dios.',
    'about.leadership': 'Nuestro Liderazgo',
    'about.pastor': 'Pastor Principal',
    'about.pastorDesc': 'Líder espiritual de nuestra comunidad por más de 15 años, dedicado a la enseñanza de la Palabra y el cuidado pastoral.',
    'about.worship': 'Líder de Alabanza',
    'about.worshipDesc': 'Ministrando a través de la música por 10 años, conduciendo a la iglesia a la presencia de Dios con adoración genuina.',
    'about.coordinator': 'Coordinadora de Células',
    'about.coordinatorDesc': 'Responsable del crecimiento y multiplicación de células, cuidando a cada líder y discipulado.',

    // ===== PRAYER WALL =====
    'prayer.title': 'Muro de Oración',
    'prayer.subtitle': '¡Comparte tu petición y ora por otros. Estamos juntos en oración!',
    'prayer.leaveRequest': 'Deja tu Petición',
    'prayer.name': 'Tu Nombre',
    'prayer.namePlaceholder': 'Ingresa tu nombre',
    'prayer.email': 'Correo Electrónico',
    'prayer.emailPlaceholder': 'Ingresa tu correo',
    'prayer.request': 'Tu Petición de Oración',
    'prayer.requestPlaceholder': 'Comparte tu petición de oración...',
    'prayer.type': 'Tipo de Petición',
    'prayer.public': 'Público',
    'prayer.publicDesc': 'Visible para que todos oren juntos',
    'prayer.private': 'Privado',
    'prayer.privateDesc': 'Solo el liderazgo tendrá acceso',
    'prayer.consent': 'Acepto el tratamiento de mis datos según RGPD',
    'prayer.send': 'Enviar Petición',
    'prayer.sending': 'Enviando...',
    'prayer.praying': 'Estoy Orando',
    'prayer.peoplePraying': 'personas orando',
    'prayer.prayingNow': 'Personas Orando Ahora',
    'prayer.anonymous': 'Anónimo',
    'prayer.requestSent': '¡Petición enviada con éxito!',
    'prayer.requestSentPublic': 'Tu petición ha sido publicada en el muro de oración.',
    'prayer.requestSentPrivate': 'Tu petición privada ha sido enviada al liderazgo.',
    'prayer.fillFields': 'Por favor, completa todos los campos y acepta los términos.',
    'prayer.recentRequests': 'Peticiones Recientes',
    'prayer.noRequests': 'Aún no hay peticiones de oración. ¡Sé el primero!',
    'prayer.joinPrayer': 'Únete en Oración',

    // ===== EVENTS SECTION =====
    'events.title': 'Eventos',
    'events.subtitle': 'Participa de nuestros cultos y eventos especiales',
    'events.upcoming': 'Próximos Eventos',
    'events.calendar': 'Calendario',
    'events.addToCalendar': 'Agregar al Calendario',
    'events.addedToCalendar': '¡Evento agregado a tu calendario!',
    'events.confirmPresence': 'Confirmar Asistencia',
    'events.presenceConfirmed': '¡Asistencia confirmada!',
    'events.location': 'Ubicación',
    'events.date': 'Fecha',
    'events.time': 'Hora',
    'events.preacher': 'Predicador',
    'events.singer': 'Alabanza',
    'events.viewDetails': 'Ver Detalles',
    'events.noEvents': 'No hay eventos programados en este momento.',
    'events.sunday': 'Domingo',
    'events.monday': 'Lunes',
    'events.tuesday': 'Martes',
    'events.wednesday': 'Miércoles',
    'events.thursday': 'Jueves',
    'events.friday': 'Viernes',
    'events.saturday': 'Sábado',
    'events.jan': 'Enero',
    'events.feb': 'Febrero',
    'events.mar': 'Marzo',
    'events.apr': 'Abril',
    'events.may': 'Mayo',
    'events.jun': 'Junio',
    'events.jul': 'Julio',
    'events.aug': 'Agosto',
    'events.sep': 'Septiembre',
    'events.oct': 'Octubre',
    'events.nov': 'Noviembre',
    'events.dec': 'Diciembre',

    // ===== GALLERY =====
    'gallery.title': 'Galería',
    'gallery.subtitle': 'Momentos especiales de nuestra comunidad',
    'gallery.all': 'Todos',
    'gallery.worship': 'Cultos',
    'gallery.events': 'Eventos',
    'gallery.cells': 'Células',
    'gallery.baptism': 'Bautismos',
    'gallery.noPhotos': 'Aún no hay fotos disponibles.',
    'gallery.viewMore': 'Ver Más Fotos',
    'gallery.close': 'Cerrar',
    'gallery.previous': 'Anterior',
    'gallery.next': 'Siguiente',

    // ===== QUIZ =====
    'quiz.title': 'Quiz Bíblico',
    'quiz.subtitle': '¡Pon a prueba tus conocimientos bíblicos y diviértete aprendiendo!',
    'quiz.start': 'Iniciar Quiz',
    'quiz.yourName': 'Tu Nombre',
    'quiz.namePlaceholder': 'Ingresa tu nombre para el ranking',
    'quiz.question': 'Pregunta',
    'quiz.of': 'de',
    'quiz.timeLeft': 'Tiempo restante',
    'quiz.seconds': 'segundos',
    'quiz.score': 'Puntuación',
    'quiz.points': 'puntos',
    'quiz.correct': '¡Correcto!',
    'quiz.incorrect': '¡Incorrecto!',
    'quiz.correctAnswer': 'Respuesta correcta',
    'quiz.next': 'Siguiente',
    'quiz.finish': 'Finalizar',
    'quiz.completed': '¡Quiz Completado!',
    'quiz.yourScore': 'Tu Puntuación',
    'quiz.ranking': 'Ranking Global',
    'quiz.position': 'Posición',
    'quiz.player': 'Jugador',
    'quiz.playAgain': 'Jugar de Nuevo',
    'quiz.share': 'Compartir Resultado',
    'quiz.excellent': '¡Excelente! ¡Eres un verdadero estudioso de la Biblia! ¡Sigue así!',
    'quiz.good': '¡Muy bien! Conoces bien las Escrituras. ¡Sigue estudiando!',
    'quiz.average': '¡Buen trabajo! Sigue leyendo la Biblia para aprender más.',
    'quiz.needsImprovement': '¡No te desanimes! La Palabra de Dios es rica. ¡Sigue estudiando!',
    'quiz.noRanking': 'Aún no hay jugadores en el ranking.',
    'quiz.enterName': 'Ingresa tu nombre para comenzar',

    // Quiz Questions
    'quiz.q1': '¿Cuántos libros tiene la Biblia?',
    'quiz.q1a1': '66',
    'quiz.q1a2': '72',
    'quiz.q1a3': '39',
    'quiz.q1a4': '27',
    'quiz.q2': '¿Quién construyó el arca?',
    'quiz.q2a1': 'Noé',
    'quiz.q2a2': 'Moisés',
    'quiz.q2a3': 'Abraham',
    'quiz.q2a4': 'David',
    'quiz.q3': '¿Cuál es el mayor mandamiento según Jesús?',
    'quiz.q3a1': 'Amar a Dios sobre todas las cosas',
    'quiz.q3a2': 'No matarás',
    'quiz.q3a3': 'Honrar padre y madre',
    'quiz.q3a4': 'No robar',
    'quiz.q4': '¿Cuántos discípulos tenía Jesús?',
    'quiz.q4a1': '12',
    'quiz.q4a2': '7',
    'quiz.q4a3': '10',
    'quiz.q4a4': '3',
    'quiz.q5': '¿Quién fue arrojado al foso de los leones?',
    'quiz.q5a1': 'Daniel',
    'quiz.q5a2': 'Jonás',
    'quiz.q5a3': 'Elías',
    'quiz.q5a4': 'José',
    'quiz.q6': '¿Dónde nació Jesús?',
    'quiz.q6a1': 'Belén',
    'quiz.q6a2': 'Nazaret',
    'quiz.q6a3': 'Jerusalén',
    'quiz.q6a4': 'Cafarnaúm',
    'quiz.q7': '¿Quién bautizó a Jesús?',
    'quiz.q7a1': 'Juan el Bautista',
    'quiz.q7a2': 'Pedro',
    'quiz.q7a3': 'Pablo',
    'quiz.q7a4': 'Santiago',
    'quiz.q8': '¿Cuántos días pasó Jesús en el desierto?',
    'quiz.q8a1': '40',
    'quiz.q8a2': '30',
    'quiz.q8a3': '7',
    'quiz.q8a4': '12',
    'quiz.q9': '¿Quién negó a Jesús tres veces?',
    'quiz.q9a1': 'Pedro',
    'quiz.q9a2': 'Judas',
    'quiz.q9a3': 'Tomás',
    'quiz.q9a4': 'Juan',
    'quiz.q10': '¿Cuál es el primer libro de la Biblia?',
    'quiz.q10a1': 'Génesis',
    'quiz.q10a2': 'Éxodo',
    'quiz.q10a3': 'Salmos',
    'quiz.q10a4': 'Mateo',

    // ===== DONATIONS =====
    'donations.title': 'Donaciones',
    'donations.subtitle': 'Tu generosidad transforma vidas y alcanza naciones',
    'donations.oneTime': 'Ofrenda Única',
    'donations.monthly': 'Mensual',
    'donations.custom': 'Otro monto',
    'donations.customPlaceholder': 'Ingresa el monto',
    'donations.method': 'Método de Pago',
    'donations.currency': 'Moneda',
    'donations.pix': 'PIX',
    'donations.mbway': 'MB WAY',
    'donations.transfer': 'Transferencia Bancaria',
    'donations.card': 'Tarjeta de Crédito',
    'donations.donate': 'Donar',
    'donations.donateNow': 'Donar Ahora',
    'donations.processing': 'Procesando...',
    'donations.thankYou': '¡Gracias por tu donación!',
    'donations.receiptSent': 'Se enviará un recibo a tu correo.',
    'donations.projectGoals': 'Metas de Proyectos',
    'donations.raised': 'recaudado',
    'donations.goal': 'meta',
    'donations.contribute': 'Contribuir',
    'donations.supporters': 'apoyadores',
    'donations.missionTrip': 'Viaje Misionero',
    'donations.missionTripDesc': 'Envía misioneros a predicar el Evangelio en regiones remotas.',
    'donations.buildingFund': 'Fondo de Construcción',
    'donations.buildingFundDesc': 'Ampliación del templo para acomodar más personas.',
    'donations.socialProject': 'Proyecto Social',
    'donations.socialProjectDesc': 'Alimentación y apoyo para familias necesitadas de la comunidad.',
    'donations.transparency': 'Transparencia',
    'donations.transparencyText': 'Todas las donaciones se utilizan con total transparencia. Informes financieros disponibles para miembros.',
    'donations.selectValue': 'Selecciona un monto',
    'donations.email': 'Correo para recibo',
    'donations.emailPlaceholder': 'tu@email.com',
    'donations.name': 'Nombre completo',
    'donations.namePlaceholder': 'Tu nombre',
    'donations.phone': 'Teléfono',
    'donations.phonePlaceholder': 'Tu teléfono',
    'donations.pixKey': 'Clave PIX',
    'donations.bankDetails': 'Datos Bancarios',
    'donations.bank': 'Banco',
    'donations.agency': 'Agencia',
    'donations.account': 'Cuenta',
    'donations.copyPix': 'Copiar Clave PIX',
    'donations.copied': '¡Copiado!',

    // ===== CELLS =====
    'cells.title': 'Células',
    'cells.subtitle': 'Encuentra una célula cerca de ti y forma parte de una familia',
    'cells.map': 'Mapa de Células',
    'cells.findNearby': 'Encontrar Célula Cercana',
    'cells.leader': 'Líder',
    'cells.day': 'Día',
    'cells.time': 'Hora',
    'cells.address': 'Dirección',
    'cells.participants': 'participantes',
    'cells.join': 'Participar',
    'cells.contact': 'Contacto',
    'cells.noCells': 'Aún no hay células registradas.',
    'cells.whatAreCells': '¿Qué son las Células?',
    'cells.whatAreCellsText': 'Las células son pequeños grupos que se reúnen semanalmente en hogares para estudiar la Biblia, orar y tener comunión juntos. Es donde la vida cristiana sucede de forma más cercana y personal.',
    'cells.benefits': 'Beneficios',
    'cells.benefit1': 'Comunión más cercana',
    'cells.benefit2': 'Crecimiento espiritual',
    'cells.benefit3': 'Apoyo mutuo',
    'cells.benefit4': 'Discipulado personal',

    // ===== MEDIA =====
    'media.title': 'Medios',
    'media.subtitle': 'Sermones, podcasts y contenidos para edificar tu fe',
    'media.sermons': 'Sermones',
    'media.podcasts': 'Podcasts',
    'media.live': 'En Vivo',
    'media.watch': 'Ver',
    'media.listen': 'Escuchar',
    'media.download': 'Descargar',
    'media.share': 'Compartir',
    'media.duration': 'Duración',
    'media.views': 'vistas',
    'media.plays': 'reproducciones',
    'media.noContent': 'Aún no hay contenido disponible.',
    'media.liveNow': 'EN VIVO AHORA',
    'media.watchLive': 'Ver Transmisión',
    'media.notLive': 'No estamos en vivo en este momento',
    'media.nextLive': 'Próxima transmisión',
    'media.subscribe': 'Suscríbete al Canal',
    'media.latestSermons': 'Últimos Sermones',
    'media.latestPodcasts': 'Últimos Podcasts',
    'media.seeAll': 'Ver Todos',
    'media.recentEpisodes': 'Episodios Recientes',

    // ===== CONTACT =====
    'contact.title': 'Contacto',
    'contact.subtitle': '¡Contáctanos! Estamos aquí para ti.',
    'contact.getInTouch': 'Contáctanos',
    'contact.name': 'Nombre',
    'contact.namePlaceholder': 'Tu nombre completo',
    'contact.email': 'Correo Electrónico',
    'contact.emailPlaceholder': 'tu@email.com',
    'contact.phone': 'Teléfono',
    'contact.phonePlaceholder': '+351 900 000 000',
    'contact.subject': 'Asunto',
    'contact.subjectPlaceholder': 'Asunto del mensaje',
    'contact.message': 'Mensaje',
    'contact.messagePlaceholder': 'Escribe tu mensaje aquí...',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.sent': '¡Mensaje enviado con éxito!',
    'contact.sentDesc': 'Responderemos pronto.',
    'contact.error': 'Error al enviar mensaje. Intenta de nuevo.',
    'contact.fillFields': 'Por favor, completa todos los campos.',
    'contact.address': 'Dirección',
    'contact.addressValue': 'Calle de la Fe, 123 - Lisboa, Portugal',
    'contact.officeHours': 'Horario de Atención',
    'contact.officeHoursValue': 'Lunes a Viernes: 9h a 18h',
    'contact.followUs': 'Síguenos',
    'contact.consent': 'Acepto el tratamiento de mis datos personales',

    // ===== SUNDAY SCHOOL =====
    'sundaySchool.title': 'Escuela Dominical',
    'sundaySchool.subtitle': 'Enseñando a los niños en el camino del Señor',
    'sundaySchool.ages': 'Edades',
    'sundaySchool.schedule': 'Horario',
    'sundaySchool.teachers': 'Maestros',
    'sundaySchool.materials': 'Materiales',
    'sundaySchool.register': 'Inscribir Niño',
    'sundaySchool.class1': 'Pequeñitos (3-5 años)',
    'sundaySchool.class2': 'Niños (6-9 años)',
    'sundaySchool.class3': 'Preadolescentes (10-12 años)',

    // ===== FOOTER =====
    'footer.description': 'Conectando vidas a Dios y transformando historias a través del amor de Cristo.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.newsletter': 'Boletín',
    'footer.newsletterText': 'Recibe novedades y contenidos edificantes.',
    'footer.emailPlaceholder': 'Tu correo',
    'footer.subscribe': 'Suscribirse',
    'footer.subscribed': '¡Suscrito con éxito!',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Uso',
    'footer.lgpd': 'RGPD',

    // ===== LOGIN =====
    'login.title': 'Entrar',
    'login.subtitle': 'Accede a tu cuenta',
    'login.username': 'Usuario',
    'login.usernamePlaceholder': 'Ingresa tu usuario',
    'login.password': 'Contraseña',
    'login.passwordPlaceholder': 'Ingresa tu contraseña',
    'login.enter': 'Entrar',
    'login.entering': 'Entrando...',
    'login.forgotPassword': '¿Olvidaste la contraseña?',
    'login.noAccount': '¿No tienes cuenta?',
    'login.register': 'Regístrate',
    'login.error': 'Usuario o contraseña inválidos',
    'login.adminHint': 'Admin: admin/123',
    'login.rememberMe': 'Recuérdame',
    'login.or': 'o',
    'login.continueWith': 'Continuar con',
    'login.close': 'Cerrar',

    // ===== MEMBER AREA =====
    'member.title': 'Área del Miembro',
    'member.welcome': 'Bienvenido',
    'member.profile': 'Mi Perfil',
    'member.donations': 'Mis Donaciones',
    'member.courses': 'Mis Cursos',
    'member.certificates': 'Certificados',
    'member.materials': 'Materiales Exclusivos',
    'member.sundaySchool': 'Escuela Dominical',
    'member.settings': 'Configuración',
    'member.editProfile': 'Editar Perfil',
    'member.changePassword': 'Cambiar Contraseña',
    'member.notifications': 'Notificaciones',
    'member.donationHistory': 'Historial de Donaciones',
    'member.downloadReceipt': 'Descargar Recibo',
    'member.noDonations': 'Ninguna donación registrada.',
    'member.courseProgress': 'Progreso del Curso',
    'member.completed': 'Completado',
    'member.inProgress': 'En Progreso',
    'member.notStarted': 'No Iniciado',
    'member.downloadCertificate': 'Descargar Certificado',
    'member.exclusiveMaterials': 'Materiales Exclusivos',
    'member.download': 'Descargar',
    'member.totalDonated': 'Total Donado',
    'member.memberSince': 'Miembro desde',

    // ===== ADMIN PANEL =====
    'admin.title': 'Panel Administrativo',
    'admin.dashboard': 'Dashboard',
    'admin.members': 'Miembros',
    'admin.events': 'Eventos',
    'admin.gallery': 'Galería',
    'admin.prayers': 'Muro de Oración',
    'admin.live': 'Lives',
    'admin.settings': 'Configuración',
    'admin.newMember': 'Nuevo Miembro',
    'admin.newEvent': 'Nuevo Evento',
    'admin.uploadPhotos': 'Subir Fotos',
    'admin.startLive': 'Iniciar Live',
    'admin.totalMembers': 'Total de Miembros',
    'admin.totalEvents': 'Total de Eventos',
    'admin.totalDonations': 'Total de Donaciones',
    'admin.pendingPrayers': 'Peticiones Pendientes',
    'admin.recentActivity': 'Actividad Reciente',
    'admin.memberGrowth': 'Crecimiento de Miembros',
    'admin.attendanceRate': 'Tasa de Asistencia',
    'admin.financialMetrics': 'Métricas Financieras',
    'admin.edit': 'Editar',
    'admin.delete': 'Eliminar',
    'admin.approve': 'Aprobar',
    'admin.reject': 'Rechazar',
    'admin.pending': 'Pendiente',
    'admin.approved': 'Aprobado',
    'admin.rejected': 'Rechazado',
    'admin.save': 'Guardar',
    'admin.cancel': 'Cancelar',
    'admin.confirm': 'Confirmar',
    'admin.confirmDelete': '¿Confirmar eliminación?',
    'admin.deleteWarning': 'Esta acción no se puede deshacer.',
    'admin.name': 'Nombre',
    'admin.email': 'Correo',
    'admin.phone': 'Teléfono',
    'admin.photo': 'Foto',
    'admin.status': 'Estado',
    'admin.active': 'Activo',
    'admin.inactive': 'Inactivo',
    'admin.date': 'Fecha',
    'admin.time': 'Hora',
    'admin.location': 'Ubicación',
    'admin.description': 'Descripción',
    'admin.poster': 'Póster',
    'admin.pastorName': 'Nombre del Pastor/Predicador',
    'admin.pastorPhoto': 'Foto del Pastor',
    'admin.singerName': 'Nombre del Cantante/Ministerio',
    'admin.singerPhoto': 'Foto del Cantante',
    'admin.eventPhotos': 'Fotos del Evento',
    'admin.category': 'Categoría',
    'admin.youtubeUrl': 'URL de YouTube',
    'admin.liveTitle': 'Título de la Live',
    'admin.goLive': 'Ir en Vivo',
    'admin.endLive': 'Terminar Live',
    'admin.viewOnYoutube': 'Ver en YouTube',
    'admin.openChannel': 'Abrir Canal',
    'admin.privateRequests': 'Peticiones Privadas',
    'admin.publicRequests': 'Peticiones Públicas',
    'admin.noMembers': 'Ningún miembro registrado.',
    'admin.noEvents': 'Ningún evento registrado.',
    'admin.noPhotos': 'Ninguna foto en la galería.',
    'admin.noPrayers': 'Ninguna petición de oración.',
    'admin.uploadPhoto': 'Subir Foto',
    'admin.selectPhoto': 'Seleccionar Foto',
    'admin.dragDrop': 'Arrastra y suelta o haz clic para seleccionar',
    'admin.maxSize': 'Tamaño máximo: 5MB',
    'admin.selectCategory': 'Selecciona una categoría',
    'admin.addMember': 'Agregar Miembro',
    'admin.addEvent': 'Agregar Evento',
    'admin.eventTitle': 'Título del Evento',
    'admin.eventDate': 'Fecha del Evento',
    'admin.eventTime': 'Hora del Evento',
    'admin.eventLocation': 'Ubicación del Evento',
    'admin.eventDescription': 'Descripción del Evento',
    'admin.eventPoster': 'Póster del Evento',
    'admin.monthlyDonations': 'Donaciones Mensuales',
    'admin.weeklyAttendance': 'Asistencia Semanal',
    'admin.liveSettings': 'Configuración de Live',
    'admin.channelUrl': 'URL del Canal',
    'admin.nextEvents': 'Próximos Eventos',
    'admin.searchMembers': 'Buscar miembros...',
    'admin.filterByStatus': 'Filtrar por estado',
    'admin.all': 'Todos',

    // ===== FLOATING WIDGETS =====
    'widget.talkToUs': 'Habla con uno de nosotros',
    'widget.needHelp': '¿Necesitas ayuda?',
    'widget.chatWhatsApp': 'Chatear en WhatsApp',
    'widget.nextService': 'Próximo Culto',
    'widget.confirmPresence': 'Confirmar Asistencia',
    'widget.yourName': 'Tu Nombre',
    'widget.yourEmail': 'Tu Correo',
    'widget.yourPhone': 'Tu Teléfono',
    'widget.confirm': 'Confirmar',
    'widget.confirmed': '¡Confirmado!',
    'widget.seeYou': '¡Hasta allá! Dios te bendiga.',
    'widget.close': 'Cerrar',
    'widget.liveNow': 'En Vivo Ahora',
    'widget.watchNow': 'Ver Ahora',
    'widget.serviceDetails': 'Detalles del Culto',
    'widget.noUpcomingService': 'Ningún culto programado',
    'widget.checkCalendar': 'Consulta nuestro calendario',

    // ===== COMMON =====
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.warning': 'Aviso',
    'common.info': 'Información',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.close': 'Cerrar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.more': 'Más',
    'common.less': 'Menos',
    'common.seeMore': 'Ver más',
    'common.seeLess': 'Ver menos',
    'common.viewAll': 'Ver todos',
    'common.required': 'Obligatorio',
    'common.optional': 'Opcional',
    'common.select': 'Seleccionar',
    'common.selected': 'Seleccionado',
    'common.noResults': 'Ningún resultado encontrado',
    'common.tryAgain': 'Intentar de nuevo',
    'common.refresh': 'Actualizar',
    'common.share': 'Compartir',
    'common.copy': 'Copiar',
    'common.copied': '¡Copiado!',
    'common.download': 'Descargar',
    'common.upload': 'Subir',
    'common.send': 'Enviar',
    'common.submit': 'Enviar',
    'common.continue': 'Continuar',
    'common.finish': 'Finalizar',
    'common.start': 'Iniciar',
    'common.stop': 'Parar',
    'common.pause': 'Pausar',
    'common.play': 'Reproducir',
    'common.today': 'Hoy',
    'common.yesterday': 'Ayer',
    'common.tomorrow': 'Mañana',
    'common.thisWeek': 'Esta semana',
    'common.thisMonth': 'Este mes',
    'common.thisYear': 'Este año',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
